config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'games#index'

  devise_for :users

  resources :games do
    resources :critics
    resources :involved_companies, only: %i[new create destroy]
  end

  resources :companies, only: %i[new create]

  get '/games/:game_id/add-genre/new', to: 'games#add_genre_new', as: 'new_game_add_genre'
  post '/games/:game_id/add-genre', to: 'games#add_genre', as: 'game_add_genres'
  delete '/games/:game_id/remove-genre/:genre_id', to: 'games#remove_genre', as: 'game_remove_genre'

  get '/games/:game_id/add-platform/new', to: 'games#add_platform_new', as: 'new_game_add_platform'
  post '/games/:game_id/add-platform', to: 'games#add_platform', as: 'game_add_platforms'
  delete '/games/:game_id/remove-platform/:platform_id', to: 'games#remove_platform', as: 'game_remove_platform'

  # devise_scope :user do
  #   root 'devise/sessions#new'
  # end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :involved_companies, dependent: :destroy
  has_many :games, through: :involved_companies

  validates :name, presence: true, uniqueness: true
end

app/models/critic.rb
class Critic < ApplicationRecord
  belongs_to :criticable, polymorphic: true
  belongs_to :user, counter_cache: true
  belongs_to :game

  validates :title, :body, presence: true
  validates :title, length: { maximum: 40 }
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :cover

  enum category: { main_game: 0, expansion: 1 }

  belongs_to :parent, class_name: 'Game', optional: true
  has_many :expansions, class_name: 'Game', foreign_key: 'parent_id',
                        inverse_of: false, dependent: :nullify
  has_many :critics, as: :criticable, dependent: :destroy
  has_and_belongs_to_many :platforms
  has_and_belongs_to_many :genres
  has_many :involved_companies, dependent: :destroy
  has_many :companies, through: :involved_companies

  validates :name, :category, presence: true
  validates :name, uniqueness: true
  validates :rating, inclusion: { in: 0..100 }, allow_nil: true
  validate :parent_validation
  validate :not_be_in_the_future

  def sorted_critics
    critics.order(created_at: :desc)
  end

  private

  def parent_validation
    if main_game?
      errors.add(:parent_id, 'Should be null if is a main game') unless parent_id.nil?
    elsif expansion?
      errors.add(:parent_id, 'Should be a valid Game id') unless Game.exists?(parent_id)
    end
  end

  def not_be_in_the_future
    return unless released_date && Time.zone.today < released_date

    errors.add(:released_date, "Shouldn't be in the future")
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :games

  validates :name, presence: true, uniqueness: true
end

app/models/involved_company.rb
class InvolvedCompany < ApplicationRecord
  belongs_to :company
  belongs_to :game

  validates :developer, :publisher, inclusion: { in: [false, true] }
  validates :company_id, uniqueness: { scope: :game_id }
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_and_belongs_to_many :games

  enum categoy: { console: 0, arcade: 1, platform: 2, operating_system: 3, portable_console: 4,
                  computer: 5 }

  validates :name, :category, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :critics, as: :criticable, dependent: :destroy

  enum role: { member: 0, admin: 1 }

  validates :email, :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  # GET /companies/new
  def new
    @company = Company.new
  end

  # POST /companies
  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :description, :start_date, :country)
  end
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  # GET /companies/new
  def new
    @company = Company.new
  end

  # POST /companies
  def create
    company = Company.new
    company.save
  end
end

app/controllers/critics_controller.rb
class CriticsController < ApplicationController
  before_action :find_game
  before_action :find_critic, only: %i[edit update]

  # GET /games/:game_id/critics/new
  def new
    @critic = @game.critics.new
  end

  # POST /games/:game_id/critics
  def create
    @critic = @game.critics.new(critic_params)
    @critic.user = current_user
    if @critic.save
      redirect_to @game
    else
      render :new
    end
  end

  # GET /games/:game_id/critics/:id/edit
  def edit; end

  # PATCH /games/:game_id/critics/:id
  def update
    if @critic.update(critic_params)
      redirect_to @game
    else
      render :edit
    end
  end

  # DELETE /games/:game_id/critics/:id
  def destroy
    @critic.destroy
    redirect_to @game
  end

  private

  def find_game
    @game = Game.find(params[:game_id])
  end

  def find_critic
    @critic = @game.critics.find(params[:id])
  end

  def critic_params
    params.require(:critic).permit(:title, :body)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, except: %i[index new create]

  # GET / || /games
  def index
    @games = Game.all
  end

  # GET /games/:id
  def show; end

  # GET /games/new
  def new
    @game = Game.new
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to root_path
    else
      render :new
    end
  end

  # GET /games/:id/edit
  def edit; end

  # PATCH /games/:id
  def update
    if @game.update(game_params)
      redirect_to @game
    else
      render :edit
    end
  end

  # DELETE /games/:id
  def destroy
    @game.destroy
    redirect_to root_path
  end

  # GET /games/:game_id/add-genre/new
  def add_genre_new
    @genre = @game.genres.new
  end

  # POST /games/:game_id/add-genre
  def add_genre
    found_genre = Genre.find(params[:genre_id])
    @game.genres << found_genre unless @game.genres.include?(found_genre)
    redirect_to @game
  end

  # DELETE /games/:game_id/remove-genre/:genre_id
  def remove_genre
    genre = Genre.find(params[:genre_id])
    @game.genres.delete(genre)
    redirect_to @game
  end

  # GET /games/:game_id/add-platform/new
  def add_platform_new
    @platform = @game.platforms.new
  end

  # POST /games/:game_id/add-platform
  def add_platform
    found_platform = Platform.find(params[:platform_id])
    @game.platforms << found_platform unless @game.platforms.include?(found_platform)
    redirect_to @game
  end

  # DELETE /games/:game_id/remove-platform/:platform_id
  def remove_platform
    platform = Platform.find(params[:platform_id])
    @game.platforms.delete(platform)
    redirect_to @game
  end

  private

  def find_game
    @game = Game.find(params[:id] || params[:game_id])
  end

  def game_params
    params.require(:game).permit(:name, :summary, :released_date, :category, :rating,
                                 :parent_id, :cover)
  end
end

app/controllers/involved_companies_controller.rb
class InvolvedCompaniesController < ApplicationController
  before_action :find_game

  # GET /games/:game_id/involved_companies/new
  def new
    @involved_company = @game.involved_companies.new
  end

  # POST /games/:game_id/involved_companies
  def create
    @involved_company = @game.involved_companies.new(involved_company_params)
    if @involved_company.save
      redirect_to @game
    else
      render :new
    end
  end

  # DELETE /games/:game_id/involved_companies/:id
  def destroy
    company = Company.find(params[:id])
    @game.involved_companies.delete(company)
    redirect_to @game
  end

  private

  def find_game
    @game = Game.find(params[:game_id])
  end

  def involved_company_params
    params.require(:involved_company).permit(:company_id, :publisher, :developer)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/critics_helper.rb
module CriticsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/involved_companies_helper.rb
module InvolvedCompaniesHelper
end

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= form_with model: @company do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>

    <div>
        <%= f.label :start_date, 'Start Date' %>
        <%= f.date_field :start_date %>
    </div>

    <div>
        <%= f.label :country %>
        <%= f.text_field :country %>
    </div>

    <div>
        <button type="button">
            <%= link_to 'Cancel', root_path %>
        </button>
        <%= f.submit 'Create Company' %>
    </div>
<% end %>

app/views/critics/edit.html.erb
<h1>Edit Critic for <%= @game.name %></h1>

<%= render "shared/critic_form", game: @game, critic: @critic do |f| %>
  <%= f.submit 'Edit Critic' %>
<% end %>

app/views/critics/new.html.erb
<h1>New Critic for <%= @game.name %></h1>

<%= render "shared/critic_form", game: @game, critic: @critic do |f| %>
  <%= f.submit 'Submit Critic' %>
<% end %>

app/views/games/add_genre_new.html.erb
<h1>Add Genre to <%= @game.name %></h1>

<%= form_with url: game_add_genres_path(@game) do |f| %>
  <div>
    <%= f.label :genre_id, 'Genre' %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: 'Please select' %>
  </div>

  <div>
    <button type='button'>
      <%= link_to 'Cancel', @game %>
    </button>
    <%= f.submit 'Add Genre' %>
  </div>
<% end %>

app/views/games/add_platform_new.html.erb
<h1>Add Platform to <%= @game.name %></h1>

<%= form_with url: game_add_platforms_path(@game) do |f| %>
    <div>
      <%= f.label :platform_id, 'Platform' %>
      <%= f.collection_select :platform_id, Platform.all, :id, :name, prompt: 'Please select' %>
    </div>
  
    <div>
      <button type='button'>
        <%= link_to 'Cancel', @game %>
      </button>
      <%= f.submit 'Add Platform' %>
    </div>
  <% end %>

app/views/games/index.html.erb
<section>
  <header>
    <h1>Games</h1>
    <% if current_user %>
      <button>
        <%= link_to 'New Company', new_company_path %>
      </button>
      <button>
        <%= link_to 'New Game', new_game_path %>
      </button>
    <% end %>
  </header>

  <section>
    <% @games.each do |game| %>
      <article>
        <h2><%= game.name %></h2>
        <span><%= game.released_date.strftime("%Y") %></span>
        <span><%= game.rating %></span>
        <p><%= game.summary.truncate(140) %></p>
        <%= game.cover.attached? ? image_tag(game.cover) : image_tag('') %>
      </article>
    <% end %>
  </section>
</section>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= form_with model: @game do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :summary %>
        <%= f.text_area :summary %>
    </div>

    <div>
        <%= f.label :released_date, 'Released Date' %>
        <%= f.date_field :released_date %>
    </div>

    <div>
        <%= f.label :category %>
        <%= f.select :category, [['Main game', 0], ['Expansion', 1]], prompt: 'Please select' %>
    </div>

    <div>
        <%= f.label :rating %>
        <%= f.number_field :rating, step: :any %>
    </div>

    <div>
        <%= f.label :parent_id, 'Parent' %>
        <%= f.collection_select :parent_id, Game.where({ category: 0 }), :id, :name, prompt: 'Please select' %>
    </div>

    <div>
        <%= f.label :cover %>
        <%= f.file_field :cover, accept: 'image/png,image/jpeg' %>
    </div>

    <div>
        <button type="button">
            <%= link_to 'Cancel', root_path %>
        </button>
        <%= f.submit 'Create Game' %>
    </div>
<% end %>

app/views/games/show.html.erb
<section>
    <article>
        <%= @game.cover.attached? ? image_tag(@game.cover) : image_tag('') %>
        <div>
            <h2><%= @game.name %></h2>
            <span>Released date: <%= @game.released_date.strftime("%B %d, %Y") %></span>
            <span><%= @game.rating %></span>
        </div>
        <div>
            <div>
                <span>Genres:</span>
                <% @game.genres.each do |genre| %>
                    <%= genre.name %>
                <% end %>
            </div>
            <div>
                <span>Platforms:</span>
                <% @game.platforms.each do |platform| %>
                    <%= platform.name %>
                <% end %>
            </div>
            <div>
                <span>Companies:</span>
                <% @game.involved_companies.each do |involved_company| %>
                    <%= involved_company.company.name %>
                <% end %>
            </div>
            <p><%= @game.summary %></p>
        </div>
    </article>
</section>
<section>
    <header>
        <span><%= @game.critics.count %> critics:</span>
        <% if current_user %>
            <button>
                <%= link_to 'New Critic', new_game_critic_path(@game) %>
            </button>
        <% end %>
    </header>
    <% @game.sorted_critics.each do |critic| %>
        <article>
            <h3><%= critic.title %></h3>
            <span>by <%= critic.user.username %> - <%= critic.created_at.strftime("%B %d, %Y") %></span>
            <p><%= critic.body %></p>
        </article>
    <% end %>
</section>

app/views/involved_companies/new.html.erb
<h1>Add Company to <%= @game.name %></h1>

<%= form_with model: [@game, @involved_company] do |f| %>
    <div>
        <%= f.label :company_id, 'Company' %>
        <%= f.collection_select :company_id, Company.all, :id, :name, prompt: 'Please select' %>
    </div>

    <div>
      <span>Involvement</span>
      <div>
        <div>
          <%= f.check_box :publisher %>
          <%= f.label :publisher %>
        </div>
        <div>
          <%= f.check_box :developer, checked: true %>
          <%= f.label :developer %>
        </div>
      </div>
    </div>

    <div>
      <button type='button'>
        <%= link_to 'Cancel', @game %>
      </button>
      <%= f.submit 'Add Company' %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CriticsGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <header>  
        <%= link_to image_tag("logo.svg"), root_path %>
        <% if current_user %>
          <div>
            <p>Loggead as, <%= link_to current_user.username, edit_user_registration_path %> </p>
            <button>
              <%= link_to 'Logout', destroy_user_session_path %>
            </button>
          </div>
        <% else %>
          <button>
            <%= link_to 'Sign In', new_user_session_path %>
          </button>
        <% end %>
      </header>

      <main>
        <%= yield %>
      </main>

      <footer>
        <h5>Critics - 2021</h5>
      </footer>
    </div>
  </body>
</html>

app/views/shared/_critic_form.html.erb
<%= form_with model: [game, critic] do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div>
    <button type="button">
      <%= link_to 'Cancel', game %>
    </button>
    <%= yield f %>
  </div>
<% end %>